version: '3.8'

services:
  frontend:
    build: 
      context: ./oceans-frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
  backend:
    build:
      context: ./oceans-backend
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - GOOGLE_APPLICATION_CREDENTIALS=/app/src/config/firebase-key.json
    volumes:
      - ./oceans-backend/src/config:/app/src/config
