version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      # Para Firebase, monta las credenciales como volumen y variable
      - GOOGLE_APPLICATION_CREDENTIALS=/app/config/firebase-key.json
    volumes:
      - ./backend/config:/app/config
